apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-summary
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-summary
          image: ghcr.io/100-hours-a-week/looper-ai-summary:1.3.0