apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-summary
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ai-summary
          image: ghcr.io/100-hours-a-week/looper-ai-summary:1.5.1
          imagePullPolicy: IfNotPresent
          env:
            - name: CHROMA_HOST
              value: "chromadb.looper-prod.svc.cluster.local"
            - name: BE_URL
              value: "http://backend.looper-prod.svc.cluster.local/api"
            - name: VLLM_URL
              value: "http://vllm-server.looper-prod.svc.cluster.local:8000"
            - name: OTEL_SERVICE_NAME
              value: "looper-ai-summary"
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://monitoring-stack-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=looper-ai-summary,service.version=1.0.0,service.namespace=looper,deployment.environment=prod"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_INSTRUMENTATION_CHROMADB_ENABLED
              value: "true"
            - name: OTEL_INSTRUMENTATION_REQUESTS_ENABLED
              value: "true"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
