apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-summary
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-summary
          image: ghcr.io/100-hours-a-week/looper-ai-summary:1.3.1
          env:
            - name: CHROMA_HOST
              value: "chromadb.looper-prod.svc.cluster.local"
            - name: BE_URL
              value: "http://backend.looper-prod.svc.cluster.local/api"
            - name: VLLM_URL
              value: "http://vllm-server.looper-prod.svc.cluster.local:8000"
