apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
spec:
  template:
    spec:
      containers:
        - name: chromadb
          env:
            - name: CHROMA_HOST
              value: "chromadb.looper-prod.svc.cluster.local"
            - name: CHROMA_OPEN_TELEMETRY__ENDPOINT
              value: "http://monitoring-stack-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: CHROMA_OPEN_TELEMETRY__SERVICE_NAME
              value: "chromadb"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://monitoring-stack-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "chromadb"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=chromadb,service.namespace=looper,deployment.environment=prod"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
