apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
spec:
  template:
    spec:
      containers:
        - name: chromadb
          env:
            - name: CHROMA_HOST
              value: "chromadb.looper-prod.svc.cluster.local"
            - name: CHROMA_OPEN_TELEMETRY__ENDPOINT
              value: "http://monitoring-stack-opentelemetry-collector.monitoring.svc.cluster.local:4318"
            - name: CHROMA_OPEN_TELEMETRY__SERVICE_NAME
              value: "chromadb"
