apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
  namespace: looper-prod
  labels:
    app: chromadb
spec:
  serviceName: chromadb-headless
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      nodeSelector:
        cloud-provider: gcp
        node-type: gpu
      tolerations:
        - key: "gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: chromadb
          image: chromadb/chroma:1.0.12
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: CHROMA_HOST
              value: "0.0.0.0"
            - name: CHROMA_PORT
              value: "8000"
            - name: CHROMA_DB_IMPL
              value: "duckdb+parquet"
            - name: CHROMA_PERSIST_DIRECTORY
              value: "/chroma/chroma"
            - name: CHROMA_SERVER_CORS_ALLOW_ORIGINS
              value: '["*"]'
          volumeMounts:
            - name: chroma-data
              mountPath: /chroma/chroma
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          readinessProbe:
            httpGet:
              path: /api/v2/heartbeat
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v2/heartbeat
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: chroma-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: openebs-local
        resources:
          requests:
            storage: 50Gi