apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: looper-prod
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/100-hours-a-week/11-ellu-fe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
