apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: looper-prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_http_version 1.1;
      proxy_set_header Connection $connection_upgrade;
      proxy_cache_bypass $http_upgrade;
      add_header 'Access-Control-Allow-Origin' 'https://dev.looper.my' always;
      add_header 'Access-Control-Allow-Credentials' 'true' always;
spec:
  ingressClassName: nginx
  rules:
    - host: dev.looper.my
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80