apiVersion: v1
kind: Service
metadata:
  name: chromadb-headless
  namespace: looper-prod
  labels:
    app: chromadb
spec:
  clusterIP: None
  selector:
    app: chromadb
  ports:
    - port: 8000
      targetPort: 8000
      name: http