apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: looper-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: redis-secrets
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: looper/dev
        property: redis-password