apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-summary
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-summary
          env:
            - name: CHROMA_HOST
              value: "chromadb.looper-dev.svc.cluster.local"
            - name: BE_URL
              value: "http://backend.looper-dev.svc.cluster.local/api"
