apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-summary-external-secret
  namespace: looper-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: ai-summary-secrets
    creationPolicy: Owner
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: looper/dev
        property: openai-api-key
    - secretKey: langchain-api-key
      remoteRef:
        key: looper/dev
        property: langchain-api-key
    - secretKey: tavily-api-key
      remoteRef:
        key: looper/dev
        property: tavily-api-key
    - secretKey: huggingface-api-key
      remoteRef:
        key: looper/dev
        property: huggingface-api-key
    - secretKey: langsmith-api-key
      remoteRef:
        key: looper/dev
        property: langsmith-api-key
    - secretKey: aws-access-key
      remoteRef:
        key: looper/dev
        property: s3-access-key
    - secretKey: aws-secret-key
      remoteRef:
        key: looper/dev
        property: s3-secret-key
    - secretKey: github-token
      remoteRef:
        key: looper/dev
        property: github-token
