apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/100-hours-a-week/looper-be:1.3.0
          env:
            - name: KAKAO_REDIRECT_URI
              value: "https://looper.my/auth/kakao/callback"
