apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/100-hours-a-week/looper-be:1.5.6
          imagePullPolicy: IfNotPresent
          env:
            - name: KAKAO_REDIRECT_URI
              value: "https://looper.my/auth/kakao/callback"
            - name: S3_BUCKET
              value: "looper-dev-image-s3"
            - name: FASTAPI_SUMMARY_URL
              value: "http://ai-summary.looper-prod.svc.cluster.local"
            - name: FASTAPI_CHATBOT_URL
              value: "http://ai-chatbot.looper-prod.svc.cluster.local"
            - name: KAFKA_BASE_URL
              value: "kafka.looper-prod.svc.cluster.local:9092"
            - name: REDIS_HOSTNAME
              value: "redis.looper-prod.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-password
            - name: OTEL_SERVICE_NAME
              value: "looper-backend"
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://monitoring-stack-opentelemetry-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=looper-backend,service.version=1.0.0,service.namespace=looper,deployment.environment=production"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
              value: "true"
            - name: OTEL_INSTRUMENTATION_JDBC_STATEMENT_SANITIZER_ENABLED
              value: "true"
            - name: OTEL_INSTRUMENTATION_KAFKA_ENABLED
              value: "true"
            - name: OTEL_INSTRUMENTATION_REDIS_ENABLED
              value: "true"
            - name: OTEL_INSTRUMENTATION_LETTUCE_ENABLED
              value: "true"
            - name: OTEL_INSTRUMENTATION_JEDIS_ENABLED
              value: "true"
            - name: SPRING_KAFKA_LISTENER_OBSERVATION_ENABLED
              value: "true"
            - name: SPRING_KAFKA_TEMPLATE_OBSERVATION_ENABLED
              value: "true"
            - name: SPRING_DATA_REDIS_OBSERVATION_ENABLED
              value: "true"
            - name: MANAGEMENT_OBSERVATIONS_KAFKA_ENABLED
              value: "true"
            - name: MANAGEMENT_OBSERVATIONS_REDIS_ENABLED
              value: "true"
            - name: OTEL_JAVAAGENT_ENABLED
              value: "true"
            - name: BP_OPENTELEMETRY_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,metrics,prometheus,opentelemetry"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dotel.java.global-autoconfigure.enabled=true"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
