apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  namespace: looper-prod
  labels:
    app: ai-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
        - name: ai-chatbot
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          image: ghcr.io/100-hours-a-week/11-ellu-chatbot-ai:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8080
          env:
