apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  namespace: looper-prod
  labels:
    app: ai-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ai-chatbot
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          image: ghcr.io/100-hours-a-week/11-ellu-chatbot-ai:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: openai-api-key
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: tavily-api-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: database_url

            # - name: OTEL_SERVICE_NAME
            #   value: "looper-chatbot"
            # - name: OTEL_SERVICE_VERSION
            #   value: "1.0.0"
            # - name: OTEL_EXPORTER_OTLP_ENDPOINT
            #   value: "http://otel-collector:4318"
            # - name: OTEL_EXPORTER_OTLP_PROTOCOL
            #   value: "http/protobuf"
            # - name: OTEL_RESOURCE_ATTRIBUTES
            #   value: "service.name=looper-chatbot,service.version=1.0.0,service.namespace=looper,deployment.environment=production"
            # - name: OTEL_METRICS_EXPORTER
            #   value: "otlp"
            # - name: OTEL_TRACES_EXPORTER
            #   value: "otlp"
            # - name: OTEL_LOGS_EXPORTER
            #   value: "otlp"
            # - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
            #   value: "true"
            # - name: OTEL_TRACES_SAMPLER
            #   value: "traceidratio"
            # - name: OTEL_TRACES_SAMPLER_ARG
            #   value: "1.0"
            # - name: OTEL_SEMCONV_STABILITY_OPT_IN
            #   value: "http"
            # - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
            #   value: "urllib3"
            # - name: OTEL_PYTHON_LOG_CORRELATION
            #   value: "true"