apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: KAKAO_REDIRECT_URI
              value: "https://dev.looper.my/auth/kakao/callback"
            - name: S3_BUCKET
              value: "looper-dev-image-s3"
