apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: KAKAO_REDIRECT_URI
              value: "https://dev.looper.my/auth/kakao/callback"
            - name: S3_BUCKET
              value: "looper-dev-image-s3"
            - name: FASTAPI_SUMMARY_URL
              value: "http://ai-summary.looper-dev.svc.cluster.local"
            - name: FASTAPI_CHATBOT_URL
              value: "http://ai-chatbot.looper-dev.svc.cluster.local"
            - name: KAFKA_BASE_URL
              value: "kafka.looper-dev.svc.cluster.local:9092"
            - name: REDIS_HOSTNAME
              value: "redis.looper-dev.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: redis-password
