apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-chatbot-external-secret
  namespace: looper-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: ai-chatbot-secrets
    creationPolicy: Owner
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: looper/dev
        property: openai-api-key
    - secretKey: tavily-api-key
      remoteRef:
        key: looper/dev
        property: tavily-api-key
    - secretKey: database_url
      remoteRef:
        key: looper/dev
        property: database_url
