apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  labels:
    app: ai-chatbot
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      nodeSelector:
        cloud-provider: aws
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ai-chatbot
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1500m
              memory: 1024Mi
          image: ghcr.io/100-hours-a-week/11-ellu-chatbot-ai:latest
          imagePullPolicy: Always #IfNotPresent 개발 서버는 태그 관리 x latest로 항상 최신 이미지 사용
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: openai-api-key
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: tavily-api-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-secrets
                  key: database_url