apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot
  labels:
    app: ai-chatbot
spec:
  type: ClusterIP
  selector:
    app: ai-chatbot
  ports:
    # 사용하는 네트워크 프로토콜
    - protocol: TCP
      port: 80
      targetPort: 8080