apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vllm-server
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:       
              memory: "12Gi"
              cpu: "2000m"