apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vllm-server-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vllm-server-secrets
    creationPolicy: Owner
  data:
    - secretKey: huggingface-api-key
      remoteRef:
        key: looper/dev
        property: huggingface-api-key