apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          env:
            - name: REDIS_HOST
              value: "redis.looper-prod.svc.cluster.local"