apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: looper-prod
  labels:
    app: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 29092
      name: internal
    - port: 9092
      name: external