apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: looper-prod
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until nc -z zookeeper.looper-prod.svc.cluster.local 2181; do
                echo "Waiting for zookeeper..."
                sleep 2
              done
              echo "Zookeeper is ready!"
        - name: setup-kafka-config
          image: apache/kafka:3.9.1
          command: ['sh', '-c']
          args:
            - |
              mkdir -p /var/kafka-logs
              cat > /tmp/server.properties << EOF
              broker.id=0
              log.dirs=/var/kafka-logs
              zookeeper.connect=zookeeper.looper-prod.svc.cluster.local:2181
              listeners=PLAINTEXT://0.0.0.0:9092
              advertised.listeners=PLAINTEXT://kafka-0.kafka-headless.looper-prod.svc.cluster.local:9092
              offsets.topic.replication.factor=1
              auto.create.topics.enable=true
              num.network.threads=3
              num.io.threads=8
              socket.send.buffer.bytes=102400
              socket.receive.buffer.bytes=102400
              socket.request.max.bytes=104857600
              log.retention.hours=168
              log.segment.bytes=1073741824
              log.retention.check.interval.ms=300000
              zookeeper.connection.timeout.ms=6000
              group.initial.rebalance.delay.ms=0
              EOF
              cp /tmp/server.properties /var/kafka-logs/
          volumeMounts:
            - name: kafka-data
              mountPath: /var/kafka-logs
      containers:
        - name: kafka
          image: apache/kafka:3.9.1
          ports:
            - containerPort: 9092
              name: kafka
          command:
            - sh
            - -c
            - |
              # Start Kafka with explicit ZooKeeper mode using our config file
              /opt/kafka/bin/kafka-server-start.sh /var/kafka-logs/server.properties
          volumeMounts:
            - name: kafka-data
              mountPath: /var/kafka-logs
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 120
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 10Gi