apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: vllm-server
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:       
              memory: "2Gi"
              cpu: "1000m"