apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vllm-server-secrets
  namespace: looper-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: vllm-server-secrets
    creationPolicy: Owner
  data:
    - secretKey: huggingface-api-key
      remoteRef:
        key: looper/prod
        property: huggingface-api-key