apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ai-chatbot
          image: ghcr.io/100-hours-a-week/looper-ai-chatbot:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: "looper-chatbot"
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://monitoring-stack-opentelemetry-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=looper-chatbot,service.version=1.0.0,service.namespace=looper,deployment.environment=prod"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
