apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-chatbot-external-secret
  namespace: looper-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: ai-chatbot-secrets
    creationPolicy: Owner
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: looper/prod
        property: openai-api-key
    - secretKey: tavily-api-key
      remoteRef:
        key: looper/prod
        property: tavily-api-key
    - secretKey: database_url
      remoteRef:
        key: looper/prod
        property: database_url
    - secretKey: langsmith-api-key
      remoteRef:
        key: looper/prod
        property: chatbot-langsmith-api-key
    - secretKey: langsmith-project
      remoteRef:
        key: looper/prod
        property: chatbot-langsmith-project