apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: looper-dev

resources:
  - namespace.yml
  - ingress.yml
  - secretstore.yml
  - ../../base/backend
  - ../../base/frontend
  - ../../base/ai-chatbot
  - ../../base/ai-summary
  - ../../base/kafka
  - ../../base/chromadb
  - ../../base/redis
  - ../../base/vllm-server
  - backend/external-secrets.yml
  - frontend/hpa.yml
  - ai-chatbot/external-secrets.yml
  - ai-summary/external-secrets.yml
  - redis/external-secrets.yml
  - vllm-server/external-secrets.yml

patches:
  - path: backend/deployment-patch.yml
    target:
      kind: Deployment
      name: backend
  - path: frontend/deployment-patch.yml
    target:
      kind: Deployment
      name: frontend
  - path: ai-chatbot/deployment-patch.yml
    target:
      kind: Deployment
      name: ai-chatbot
  - path: ai-summary/deployment-patch.yml
    target:
      kind: Deployment
      name: ai-summary
  - path: chromadb/statefulset-patch.yml
    target:
      kind: StatefulSet
      name: chromadb
  - path: kafka/statefulset-patch.yml
    target:
      kind: StatefulSet
      name: kafka
  - path: redis/statefulset-patch.yml
    target:
      kind: StatefulSet
      name: redis
  - path: vllm-server/deployment-patch.yml
    target:
      kind: Deployment
      name: vllm-server